name: Build

on:
  push:
    branches:
      - "**"

jobs:
  release:
    uses: mathisdt/workflows/.github/workflows/maven.yaml@master
    with:
      files-to-release: |
        target/teachernotes-extractor-*.jar
    secrets: inherit

